### ISSUE TITLE
[Android Bootcamp] Project 0 Todo - ready for review

### ISSUE THREAD

**Issue by koulmomo** [koulmomo/SimpleTodo#2]
My app is complete, please review. /cc @codepathreview @codepath

**Comment by nidhi1608** [comment]
Mo,

Looks great! This was intended in part to give you an introduction to the general rhythm of this course. The course is entirely project based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer to learn all practical Android development and best practices as quickly as possible. We also do a code review for each submitted project.
Nice job with the project, hope you found it as a helpful introduction.

Look forward to seeing you in the class! In the mean time, you may consider working on [extensions to your todo app](http://courses.codepath.com/snippets/intro_to_android/prework#heading-5-extending-your-todo) and let us know if you have any questions.
